// Auto-generated ticker → company name map for AI Cockpit display
// Covers S&P 500, NDX 100, and extended elastic scanner universe
const TICKER_NAMES: Record<string, string> = {
  AAPL: "Apple", ABBV: "AbbVie", ABT: "Abbott Labs", ACN: "Accenture", ADBE: "Adobe",
  ADEA: "Adeia", ADI: "Analog Devices", ADM: "Archer-Daniels", ADP: "ADP", ADSK: "Autodesk",
  ADUS: "Addus HomeCare", AEE: "Ameren", AEP: "American Electric", AES: "AES Corp",
  AFL: "Aflac", AGYS: "Agilysys", AIG: "AIG", AIZ: "Assurant", AJG: "Arthur J Gallagher",
  AKAM: "Akamai", ALB: "Albemarle", ALGN: "Align Tech", ALK: "Alaska Air",
  ALL: "Allstate", ALLE: "Allegion", AMAT: "Applied Materials", AMCR: "Amcor",
  AMD: "AMD", AME: "Ametek", AMGN: "Amgen", AMN: "AMN Healthcare",
  AMP: "Ameriprise", AMTM: "Amentum", AMZN: "Amazon", ANIP: "ANI Pharma",
  ANET: "Arista Networks", ANSS: "Ansys", AON: "Aon", AOS: "A.O. Smith",
  APA: "APA Corp", APD: "Air Products", APH: "Amphenol", APO: "Apollo Global",
  APTV: "Aptiv", ARE: "Alexandria RE", ATO: "Atmos Energy",
  AVA: "Avista", AVB: "AvalonBay", AVGO: "Broadcom", AVY: "Avery Dennison",
  AWK: "American Water", AXSM: "Axsome Therapeutics", AXP: "American Express",
  AZO: "AutoZone", BA: "Boeing", BAC: "Bank of America", BAX: "Baxter",
  BBWI: "Bath & Body Works", BBY: "Best Buy", BC: "Brunswick Corp",
  BDX: "Becton Dickinson", BEN: "Franklin Resources",
  BHE: "Benchmark Electronics", BIO: "Bio-Rad", BK: "Bank of NY Mellon",
  BKE: "Buckle", BKNG: "Booking Holdings", BKR: "Baker Hughes",
  BLDR: "Builders FirstSource", BLK: "BlackRock", BMY: "Bristol-Myers",
  BOH: "Bank of Hawaii", BR: "Broadridge",
  BRO: "Brown & Brown", BSX: "Boston Scientific", BWA: "BorgWarner",
  BXP: "BXP Inc", C: "Citigroup", CAG: "Conagra", CAH: "Cardinal Health",
  CALX: "Calix", CARR: "Carrier Global", CAT: "Caterpillar", CB: "Chubb",
  CBOE: "Cboe Global", CBRE: "CBRE Group", CCI: "Crown Castle",
  CCK: "Crown Holdings", CCL: "Carnival",
  CDNS: "Cadence Design", CDW: "CDW Corp", CE: "Celanese",
  CENTA: "Central Garden", CEG: "Constellation Energy", CF: "CF Industries",
  CFG: "Citizens Financial", CHD: "Church & Dwight", CHRW: "C.H. Robinson",
  CHTR: "Charter Comm", CI: "Cigna", CIEN: "Ciena Corp",
  CINF: "Cincinnati Financial", CL: "Colgate-Palmolive", CLX: "Clorox",
  CMA: "Comerica", CMCSA: "Comcast", CME: "CME Group", CMG: "Chipotle",
  CMI: "Cummins", CMS: "CMS Energy", CNC: "Centene", CNP: "CenterPoint",
  COF: "Capital One", COO: "CooperCompanies", COP: "ConocoPhillips",
  COR: "Cencora", COST: "Costco", CPB: "Campbell Soup", CPRT: "Copart",
  CPT: "Camden Property", CR: "Crane Co", CRL: "Charles River Labs",
  CRM: "Salesforce", CSCO: "Cisco", CSGP: "CoStar Group",
  CSX: "CSX Corp", CTAS: "Cintas", CTRA: "Coterra Energy",
  CTSH: "Cognizant", CTVA: "Corteva", CUBE: "CubeSmart",
  CVS: "CVS Health", CVX: "Chevron", CZR: "Caesars Entertainment",
  D: "Dominion Energy", DAL: "Delta Air Lines", DAR: "Darling Ingredients",
  DD: "DuPont", DE: "Deere & Co", DELL: "Dell Technologies",
  DFS: "Discover Financial", DG: "Dollar General", DGX: "Quest Diagnostics",
  DHI: "D.R. Horton", DHR: "Danaher", DIS: "Walt Disney",
  DLR: "Digital Realty", DLTR: "Dollar Tree",
  DOC: "Healthpeak", DORM: "Dorman Products", DOV: "Dover Corp",
  DOW: "Dow Inc", DPZ: "Domino's Pizza", DRI: "Darden Restaurants",
  DTE: "DTE Energy", DUK: "Duke Energy", DVA: "DaVita", DVN: "Devon Energy",
  DXCM: "DexCom", EA: "Electronic Arts", EBAY: "eBay",
  ECL: "Ecolab", ED: "Consolidated Edison", EFX: "Equifax",
  EIX: "Edison International", EL: "Estée Lauder", EMN: "Eastman Chemical",
  EMR: "Emerson Electric", ENPH: "Enphase Energy", ENVA: "Enova International",
  EOG: "EOG Resources", EPAM: "EPAM Systems", EQIX: "Equinix",
  EQH: "Equitable Holdings", EQR: "Equity Residential", EQT: "EQT Corp",
  ES: "Eversource", ESS: "Essex Property", ETN: "Eaton Corp",
  ETR: "Entergy", EVRG: "Evergy", EW: "Edwards Lifesciences",
  EWBC: "East West Bancorp", EXC: "Exelon", EXPD: "Expeditors",
  EXPE: "Expedia", EXR: "Extra Space Storage",
  F: "Ford Motor", FANG: "Diamondback Energy", FAST: "Fastenal",
  FBHS: "Fortune Brands", FCX: "Freeport-McMoRan", FDS: "FactSet",
  FDX: "FedEx", FE: "FirstEnergy", FFIV: "F5 Networks",
  FG: "F&G Annuities", FIS: "Fidelity National", FISV: "Fiserv",
  FITB: "Fifth Third", FIX: "Comfort Systems",
  FMC: "FMC Corp", FORM: "FormFactor", FOX: "Fox Corp",
  FRT: "Federal Realty", FSLR: "First Solar",
  FTNT: "Fortinet", FTV: "Fortive", FUL: "H.B. Fuller",
  GATX: "GATX Corp", GD: "General Dynamics", GDDY: "GoDaddy",
  GE: "GE Aerospace", GEHC: "GE HealthCare", GEN: "Gen Digital",
  GEV: "GE Vernova", GILD: "Gilead Sciences", GIS: "General Mills",
  GL: "Globe Life", GLW: "Corning", GM: "General Motors",
  GNRC: "Generac", GOOG: "Alphabet", GOOGL: "Alphabet",
  GPC: "Genuine Parts", GPN: "Global Payments", GRMN: "Garmin",
  GS: "Goldman Sachs", GWW: "W.W. Grainger",
  HAL: "Halliburton", HAS: "Hasbro", HBAN: "Huntington Bancshares",
  HCA: "HCA Healthcare", HD: "Home Depot", HL: "Hecla Mining", HOLX: "Hologic",
  HON: "Honeywell", HPE: "Hewlett Packard Ent.", HPQ: "HP Inc",
  HRL: "Hormel Foods", HSIC: "Henry Schein", HST: "Host Hotels",
  HSY: "Hershey", HUBB: "Hubbell", HUM: "Humana", HWM: "Howmet Aerospace",
  IBM: "IBM", ICE: "Intercontinental Exchange", IDXX: "Idexx Labs",
  IEX: "IDEX Corp", IFF: "IFF", ILMN: "Illumina", INCY: "Incyte",
  INTC: "Intel", INTU: "Intuit", INVH: "Invitation Homes",
  IP: "International Paper", IPG: "Interpublic", IQV: "IQVIA",
  IR: "Ingersoll Rand", IRM: "Iron Mountain", ISRG: "Intuitive Surgical",
  IT: "Gartner", ITW: "Illinois Tool Works",
  J: "Jacobs Solutions", JBHT: "J.B. Hunt", JBTM: "JBT Marel",
  JCI: "Johnson Controls", JKHY: "Jack Henry", JNJ: "Johnson & Johnson",
  JNPR: "Juniper Networks", JPM: "JPMorgan Chase",
  K: "Kellanova", KDP: "Keurig Dr Pepper", KEY: "KeyCorp",
  KEYS: "Keysight", KGS: "Kodiak Gas Services", KHC: "Kraft Heinz",
  KIM: "Kimco Realty", KLAC: "KLA Corp", KMB: "Kimberly-Clark",
  KMI: "Kinder Morgan", KMX: "CarMax", KO: "Coca-Cola", KR: "Kroger",
  L: "Loews Corp", LDOS: "Leidos", LEN: "Lennar",
  LH: "LabCorp", LHX: "L3Harris", LIN: "Linde",
  LKQ: "LKQ Corp", LLY: "Eli Lilly", LMT: "Lockheed Martin",
  LNT: "Alliant Energy", LOW: "Lowe's", LRCX: "Lam Research",
  LULU: "Lululemon", LUV: "Southwest Airlines", LVS: "Las Vegas Sands",
  LW: "Lamb Weston", LYB: "LyondellBasell", LYV: "Live Nation",
  MA: "Mastercard", MAA: "Mid-America Apartment", MAR: "Marriott",
  MAS: "Masco", MCD: "McDonald's", MCHP: "Microchip Technology",
  MCK: "McKesson", MCO: "Moody's", MDLZ: "Mondelez",
  MDT: "Medtronic", MET: "MetLife", META: "Meta Platforms",
  MGM: "MGM Resorts", MHK: "Mohawk Industries", MKC: "McCormick",
  MKTX: "MarketAxess", MLM: "Martin Marietta", MMC: "Marsh & McLennan",
  MMM: "3M", MNST: "Monster Beverage", MO: "Altria Group",
  MOH: "Molina Healthcare", MOS: "Mosaic Co", MPC: "Marathon Petroleum",
  MPWR: "Monolithic Power", MRK: "Merck", MRNA: "Moderna",
  MRVL: "Marvell Technology", MS: "Morgan Stanley",
  MSCI: "MSCI Inc", MSFT: "Microsoft", MSGS: "MSG Sports",
  MSI: "Motorola Solutions", MTB: "M&T Bank", MTCH: "Match Group",
  MTD: "Mettler-Toledo", MU: "Micron Technology",
  NCLH: "Norwegian Cruise", NDAQ: "Nasdaq", NDSN: "Nordson",
  NEE: "NextEra Energy", NEM: "Newmont", NFLX: "Netflix",
  NI: "NiSource", NKE: "Nike", NOC: "Northrop Grumman",
  NOW: "ServiceNow", NRG: "NRG Energy", NSC: "Norfolk Southern",
  NTAP: "NetApp", NTRS: "Northern Trust", NUE: "Nucor",
  NVDA: "NVIDIA", NVR: "NVR Inc", NWL: "Newell Brands",
  NWS: "News Corp", NXPI: "NXP Semiconductors",
  O: "Realty Income", ODFL: "Old Dominion Freight", OKE: "ONEOK",
  OMC: "Omnicom", ON: "ON Semiconductor", ORCL: "Oracle",
  ORLY: "O'Reilly Auto", OTIS: "Otis Worldwide", OXY: "Occidental",
  PANW: "Palo Alto Networks", PARA: "Paramount Global", PAYC: "Paycom",
  PAYX: "Paychex", PBH: "Prestige Brands", PCAR: "PACCAR",
  PCG: "PG&E Corp", PEG: "PSEG",
  PEP: "PepsiCo", PFE: "Pfizer", PFG: "Principal Financial",
  PG: "Procter & Gamble", PGR: "Progressive", PH: "Parker Hannifin",
  PHM: "PulteGroup", PKG: "Packaging Corp", PLD: "Prologis",
  PLUS: "ePlus", PM: "Philip Morris", PNC: "PNC Financial",
  PNR: "Pentair", PNW: "Pinnacle West", POOL: "Pool Corp",
  PPG: "PPG Industries", PPL: "PPL Corp", PRDO: "Perdoceo Education",
  PRU: "Prudential", PSA: "Public Storage", PSX: "Phillips 66",
  PTC: "PTC Inc", PVH: "PVH Corp", PWR: "Quanta Services",
  PYPL: "PayPal",
  QCOM: "Qualcomm", QRVO: "Qorvo",
  RCL: "Royal Caribbean", RE: "Everest Group", REG: "Regency Centers",
  REGN: "Regeneron", RF: "Regions Financial", RHI: "Robert Half",
  RJF: "Raymond James", RL: "Ralph Lauren", RLI: "RLI Corp",
  RMD: "ResMed", ROK: "Rockwell Automation", ROKU: "Roku",
  ROL: "Rollins", ROP: "Roper Technologies", ROST: "Ross Stores",
  RSG: "Republic Services", RTX: "RTX Corp",
  SBAC: "SBA Communications", SBUX: "Starbucks",
  SCHW: "Charles Schwab", SCSC: "ScanSource",
  SHW: "Sherwin-Williams",
  SJM: "J.M. Smucker", SLB: "SLB", SNA: "Snap-on",
  SNPS: "Synopsys", SO: "Southern Co", SPG: "Simon Property",
  SPGI: "S&P Global", SRE: "Sempra", STC: "Stewart Info",
  STE: "STERIS", STLD: "Steel Dynamics", STT: "State Street",
  STX: "Seagate", STZ: "Constellation Brands", SWK: "Stanley Black & Decker",
  SWKS: "Skyworks Solutions", SYF: "Synchrony Financial",
  SYK: "Stryker", SYY: "Sysco",
  T: "AT&T", TAP: "Molson Coors", TDG: "TransDigm",
  TDY: "Teledyne", TECH: "Bio-Techne", TEL: "TE Connectivity",
  TER: "Teradyne", TFC: "Truist Financial", TFX: "Teleflex",
  TGT: "Target", TJX: "TJX Companies", TMO: "Thermo Fisher",
  TMUS: "T-Mobile", TPR: "Tapestry", TRGP: "Targa Resources",
  TRMB: "Trimble", TROW: "T. Rowe Price", TRV: "Travelers",
  TSCO: "Tractor Supply", TSLA: "Tesla", TSN: "Tyson Foods",
  TT: "Trane Technologies", TTWO: "Take-Two", TXN: "Texas Instruments",
  TXT: "Textron", TYL: "Tyler Technologies",
  UAL: "United Airlines", UBER: "Uber", UDR: "UDR Inc",
  UHS: "Universal Health", ULTA: "Ulta Beauty",
  UNF: "UniFirst", UNH: "UnitedHealth", UNP: "Union Pacific",
  UPS: "UPS", URI: "United Rentals", USB: "U.S. Bancorp",
  UTL: "Unitil Corp",
  V: "Visa", VFC: "VF Corp", VICI: "VICI Properties",
  VLO: "Valero Energy", VMC: "Vulcan Materials", VRSK: "Verisk",
  VRSN: "VeriSign", VRTX: "Vertex Pharma", VST: "Vistra",
  VTR: "Ventas", VTRS: "Viatris", VZ: "Verizon",
  WAB: "Wabtec", WAT: "Waters Corp", WBA: "Walgreens Boots",
  WBD: "Warner Bros Discovery", WDC: "Western Digital",
  WEC: "WEC Energy", WELL: "Welltower", WFC: "Wells Fargo",
  WHR: "Whirlpool", WM: "Waste Management", WMB: "Williams Companies",
  WMG: "Warner Music", WMT: "Walmart", WRB: "W.R. Berkley",
  WRK: "WestRock", WST: "West Pharma", WTW: "Willis Towers Watson",
  WY: "Weyerhaeuser",
  XEL: "Xcel Energy", XOM: "ExxonMobil", XRAY: "Dentsply Sirona",
  XYL: "Xylem",
  YUM: "Yum! Brands",
  ZBH: "Zimmer Biomet", ZBRA: "Zebra Technologies", ZION: "Zions Bancorp",
  ZTS: "Zoetis",
};

export function getCompanyName(ticker: string): string | undefined {
  return TICKER_NAMES[ticker.toUpperCase()];
}

export default TICKER_NAMES;
